### PR TITLE
Win32 application manifests

### PR DESCRIPTION
**Pull request by thehatkid**
- Add Win32 application manifest to ModShot and ModShot shim executables
- Add linker args (`--(major/minor)-subsystem-version`, `--(major/minor)-os-version`) for setting Windows subversion and OS version to 6.00 (Windows Vista/7)
- Fixed messagebox title due to duplicate strings

### CODE REVIEW

**Review by melody-rs — CHANGES_REQUESTED** [review]
Can you set the subversion manifest to windows 10?

**Comment by thehatkid** [comment]
> set subversion manifest to windows 10

What do you mean? Like I did set the minimal subversion/OS to 6.00 because on Windows XP it won't run nicely, and [fix window styles](https://raymai97.github.io/myblog/subsystem-version-and-ws-thickframe)
If you mean add support in manifest XML file - it's already have.

**Comment by melody-rs** [comment]
> Add linker args (--(major/minor)-subsystem-version, --(major/minor)-os-version) for setting Windows subversion and OS version to 6.00 (Windows Vista/7)

**Comment by thehatkid** [comment]
No? Like I had said ModShot can runs on Windows Vista and higher (7, 8, 8.1, 10, 11), and I did set __minimal subsystem version__. It still runs on Windows 10.

And if I will try set to 10.0 directly via built-in Visual Studio tool `editbin.exe` it won't run if value is higher than `6.2`.

You can see [what does `/SUBSYSTEM` in Microsoft Docs](https://docs.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-170#remarks)

**Review by melody-rs — APPROVED** [review]

**Pull request merged**
