### PR TITLE
Move to another modules (#60 w/ code reviewed)

### PR DESCRIPTION
**Pull request by thehatkid**
(code reviewed from Astrabit-ST/ModShot-Core#60)

### CODE REVIEW

**Review by melody-rs — CHANGES_REQUESTED** [review]
Do you think you could merge `Modshot` and `ModWindow` into one module?

**Comment by thehatkid** [comment]
> Do you think you could merge `Modshot` and `ModWindow` into one module?

Sure, because it's likely comes same from ModShot so why not (if you means merge into `modshot-binding.cpp`)

**Comment by melody-rs** [comment]
Yep, that would be great!

**Comment by thehatkid** [comment]
Now merged in f8a132f58638d7ba637b89c5af76a9ba0c5d765a

**Review by melody-rs — APPROVED** [review]
Looks good! I might move the `ModWindow` functions onto `Modshot` in the future.

**Pull request merged**
