### PR TITLE
Revert "ModShot fixes and notifications/balloons"

### PR DESCRIPTION
**Pull request by melody-rs**
Reverts Astrabit-ST/ModShot-Core#60

### CODE REVIEW

**Comment by servantoftestator** [comment]
Did they forget to squash before merge or something.

**Comment by melody-rs** [comment]
No, they didn't let me review the PR, and there's some things I would like them to change first

**Comment by servantoftestator** [comment]
*glances at commit* Looks like it at a minimum could be split into two different PR's.

**Comment by melody-rs** [comment]
Look, I've never been in this situation before, and I'm no professional, give me a break.

**Comment by servantoftestator** [comment]
Oh sorry I wasn't trying to critique you speak2erase. I was just talking about how on hatkid's part the notifications/balloons and the minor fixes could be split into two pr's for easier review.

**Comment by thehatkid** [comment]
So, should I revert reverting PR and create one more PR that was code reviewed? (something like 2 PRs in total)

**Comment by melody-rs** [comment]
That would be great!

**Pull request merged**
